# Generated by Django 4.2.14 on 2024-07-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
